### ISSUE TITLE
needed discussion on the receiver ?

### ISSUE THREAD

**Issue by NicoKos** [irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport#10]
The current version of hte draft seems to go for a more "server" side discussion. 
We should not forget to speak about the client.

**Comment by mwelzl** [comment]
I agree - but maybe delay this until the next version of the draft?

**Comment by NicoKos** [comment]
I have pushed some content with some more details on the server side solutions. 
I think we may be soon ready to either submit this version or had a small section on the receiver side. It can be very simple IMHO: 

" The receiver must not use CC channel signals to acknowledge the recovery of data packets with the coding schemes. The information on recovered packets must be reported on the FEC channel."

**Comment by mwelzl** [comment]
I agree with both approaches. I'd vote for shipping it as-is  (better to have a more useful discussion on the receiver side - surely we can come up with something more for the next version of the draft?)

**Comment by NicoKos** [comment]
Thanks for the feedback - I would vote the same. Any other thoughts ?

**Comment by NicoKos** [comment]
This is done in PR #23
