### ISSUE TITLE
Propose concrete examples and consider different application profiles

### ISSUE THREAD

**Issue by NicoKos** [irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport#17]
- I see a major scoping problem in these sections.
What does this document really aim at? It is said earlier:
   This document discusses how FEC and CC relate.
Here we see architectural discussions on advantages/drawbacks instead.
There is also the additional idea of how it relates to transport reliability
mechanism which is (in theory) out of scope.

- I'd like to see more info about what concretely can be done (examples).
The case of QUIC and what was already proposed here to let FEC and CC work
together is pretty interesting.

- I also think the application (as data source) is potentially involved
in the big picture: an application generating a real-time data flow
is not the same as an application generating background traffic.
In the first case we could end up with situations where it's just impossible
to carry traffic by adding a certain redundancy, given the network conditions.
It means that without adapting the data flow there is probably no solution.
In the second case (which includes François's experiments with tail losses)

**Comment by mwelzl** [comment]
item 1: I think this is now addressed by careful phrasing in the para that mentions reliability, in PR #22.
Item 2: I agree but I'd greatly prefer if we could postpone this to the next version. I think we should include multipath considerations too, so this will be quite a bit of work.
Item 3: I agree... someone should write something :)

**Comment by NicoKos** [comment]
Item 1 addressed by PR #22 

Open for next submission

I'd like to see more info about what concretely can be done (examples).
The case of QUIC and what was already proposed here to let FEC and CC work
together is pretty interesting.

I also think the application (as data source) is potentially involved
in the big picture: an application generating a real-time data flow
is not the same as an application generating background traffic.
In the first case we could end up with situations where it's just impossible
to carry traffic by adding a certain redundancy, given the network conditions.
It means that without adapting the data flow there is probably no solution.
In the second case (which includes François's experiments with tail losses)

**Comment by francoismichel** [comment]
I am not sure I completely get the last item though. More specifically, I don't know what to say about this in this draft about the relations between coding and the congestion control.

We could state that the application can provide information about importance or deadline concerning its data, but I think the optimal FEC pattern , with or without congestion, will likely depend on the application's requirements in the end ? 

Does anybody have a clearer idea on what we could state on this ? Let's discuss this here before writing ?

**Comment by mwelzl** [comment]
I think you're trying to find a solution, whereas we're only describing a situation. The latter is simpler: we can basically repeat what Vincent has told us: "an application generating a real-time data flow
is not the same as an application generating background traffic.
In the first case we could end up with situations where it's just impossible
to carry traffic by adding a certain redundancy, given the network conditions.
It means that without adapting the data flow there is probably no solution."

Just point it out.

**Comment by francoismichel** [comment]
Looks good to me. Thank you !

**Comment by NicoKos** [comment]
The application requirements aspect have been covered by PR #23
