### ISSUE TITLE
The FEC channel currently needs source packets to repair stuff

### ISSUE THREAD

**Issue by francoismichel** [irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport#21]
The title of the document is "Coding and congestion control in transport" but we only present a "FEC Channel" that only carries repair packets and some signaling about the repaired packets.

I like the idea of two separated channels a lot, but I think we also should integrate source packets as part of the FEC channel, and maybe rename the FEC channel to "Coding Channel" and "packets" to "symbols" when we talk about the coding channel ? 

Here is what I propose concretely:

- The CC channel stays unchanged, it carries packets
- The FEC channel becomes a Coding channel and carries *symbols*: Source Symbols and Repair Symbols. I think the approach there is more general: one network packet can contain several Source/Repair Symbols (similarly to the coding-for-quic draft). I think this helps to isolate both CC and FEC channels from each others as the FEC/Coding channel only plays with Symbols while the CC channel plays with packets.

When I read the current design, it makes me think that the FEC channel needs the source packets from the CC channel to decode the received repair packets but this is shown nowhere in the graph. By considering different entities (packets VS symbols that are in fact a view on the sent/received data), we decorrelate more intuitively the FEC and the CC channels. As a consequence, we will only talk about symbols when it concerns the Coding channel and packets when it concerns the CC channel.

What do you think ?

I do not think this is an urging change by the way.

**Comment by elochin** [comment]
Hi,

Coding channel refers to physical layer and when combined with the term 
symbol, it also refers to physical operations which are not those at 
packet level.
We stated in RFC8406 that

       Generally speaking, a Packet is the unit of data that is sent in
       the Packet Erasure Channel, while a Symbol is the unit of data
       that is manipulated during the encoding and decoding operations.

So we allow the use of symbol only when it corresponds to non yet 
transmitted data. As soon as transmitted, it becomes a packet.

EL

-- 
Emmanuel LOCHIN
Professeur ISAE
ISAE SUPAERO - Institut Supérieur de l'Aéronautique et de l'Espace
10 avenue Edouard Belin - BP 54032 - 31055 TOULOUSE CEDEX 4 FRANCE -
http://www.isae-supaero.fr
Tel +33 5 61 33 84 85 - Fax (+33) 5 61 33 83 45
Web : http://personnel.isae.fr/emmanuel-lochin/

**Comment by francoismichel** [comment]
Hello,

> Coding channel refers to physical layer and when combined with the term
symbol, it also refers to physical operations which are not those at
packet level.

Hmm, in that case, renaming the channel this way would make it more confusing I agree, sorry for that then :-)

> So we allow the use of symbol only when it corresponds to non yet
transmitted data. As soon as transmitted, it becomes a packet.

I think the definition I proposed here still fits with the symbol definition you described though. A packet can contain more than 1 source/repair symbol(s) and the source symbols can be different than what is actually sent on the wire (e.g. source symbols can contain padding that is not actually sent on the wire or can contain metadata that are not sent on the wire either). So I still think that it matches more the definition of symbols than packets. All the real packets received by a protocol can be processed and transformed into source symbols before being passed to the FEC Channel. (sorry in advance if I have misconceptions on this matter)

**Comment by elochin** [comment]
Yes in that context it's fine and we stick to RFC8406.

**Comment by NicoKos** [comment]
Done in PR #29
