### ISSUE TITLE
be clear that this is a discussion (and not recommendation) draft

### ISSUE THREAD

**Issue by NicoKos** [irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport#27]
From IETF108 : 
There seems to be a consensus that the document is a discussion draft and not a recommendation draft.

**Comment by francoismichel** [comment]
Okay, so if I understand correctly, the revised objective of this draft is to describe how FEC and CC co-exist (and *not* interact ;-) ), and what can be the consequences. Am I right ?

**Comment by NicoKos** [comment]
i agree - also the discussion for researchers comparing coding mechanisms

**Comment by mwelzl** [comment]
I don't understand Francois' "and _not_ interact" part. What do you mean? Why is it not about discussing interactions?

**Comment by NicoKos** [comment]
Looking back at this, I think that while the document is not a 'recommendation' draft in terms of IETF language, there should be some strong discussions - such as not hiding congestion signals. 
i guess the draft discuss interactions and the issue could be closed.

**Comment by francoismichel** [comment]
> I don't understand Francois' "and not interact" part. What do you mean? Why is it not about discussing interactions?

In my view, these two mechanisms (loss recovery and congestion control) do coexist but do not necessarily interact that much (I may miss some examples of interactions), I would say the discussion here is more about interferences, i.e. hiding or not the loss information to the congestion control, but I do not necessarily see that as interactions as one (loss recovery) is hiding the losses without the other (CC) knowing it. In my point of view, we can dissociate the loss recovery mechanism from the loss detection mechanism that indeed sends signals that are valuable to the CC. But this loss detection mechanism can be independant from the loss recovery one: whether we use FEC or SR-ARQ will likely not have an impact on how we detect lost packets.
