### ISSUE TITLE
Comments on 5.2 "Discussion"

### ISSUE THREAD

**Issue by elochin** [irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport#33]
Not quite sure to understand here: "a secondary congestion control could be introduced underneath the FEC layer" -> so it means doing CC at an equivalent link-layer? Point-to-point?

**Comment by NicoKos** [comment]
Texte update in branch prep_ietf_109
Please close the issue if the update is OK for you.

**Comment by mwelzl** [comment]
This is for @elochin to answer or close; I'm just adding here that *I* am ok with the update addressing this now.

**Comment by elochin** [comment]
OK
