### ISSUE TITLE
Missing research section

### ISSUE THREAD

**Issue by NicoKos** [irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport#34]
Marie-José

I am following the evolution
of this draft and while the issues are starting to be well covered this is
RG document so while I approve of the changes it would be nice to highlight
the research that is still needed.

Michael 

Regarding Marie-José's comment: I agree, and I think that we could approach this by trying to find at least one published example of research per category - ideally the "best" per category. This would show, wherever we find something, what the SoA is - research could focus on improving this SoA. Also, it would probably give us some holes - e.g., I don't think there's any much research on (e2e!) FEC "below the transport", especially using multiple CC instances as hinted on in the draft. These holes would let us identify missing research.

**Comment by francoismichel** [comment]
I see two examples of FEC **below the transport**, maybe am I forgetting other ones.

- SUNDARARAJAN, Jay Kumar, SHAH, Devavrat, MÉDARD, Muriel, et al. Network coding meets TCP: Theory and implementation. Proceedings of the IEEE, 2011, vol. 99, no 3, p. 490-512. (https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=5688180)  There is a variant with MPTCP (https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=6692295)
- Tetrys (https://tools.ietf.org/html/draft-detchart-nwcrg-tetrys-04) can be used below the transport as a tunnel as discussed here: https://www.ietf.org/proceedings/100/slides/slides-100-nwcrg-07-lochin-on-the-joint-use-of-tcp-and-network-coding-00.pdf

For the use of FEC **inside the transport** I know that there is a use of FEC with RTP and WebRTC, I saw it in the source code of some browsers but I don't know a well-cited research paper about this. There are RFCs however: https://tools.ietf.org/html/rfc5109 and this very short article: https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=6738383

For QUIC, I know three articles proposing FEC inside the transport:

- Michel, F., De Coninck, Q., & Bonaventure, O. (2019, May). QUIC-FEC: Bringing the benefits of Forward Erasure Correction to QUIC. In 2019 IFIP Networking Conference (IFIP Networking) (pp. 1-9). IEEE. (https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8816838) -> use of a RECOVERED frame to indicate when a packet is recovered and does not hide the losses to the congestion control
- GARRIDO, Pablo, SANCHEZ, Isabel, FERLIN, Simone, et al. rQUIC: Integrating FEC with QUIC for Robust Wireless Communications. In : 2019 IEEE Global Communications Conference (GLOBECOM). IEEE, 2019. p. 1-7.  (https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8999454) -> they seem to hide the congestion-induced losses to cubic using FEC to increase their bitrate (but no clear discussion on that)
- PALMER, Mirko, KRÜGER, Thorben, CHANDRASEKARAN, Balakrishnan, et al. The quic fix for optimal video streaming. In : Proceedings of the Workshop on the Evolution, Performance, and Interoperability of QUIC. 2018. p. 43-49. (https://arxiv.org/pdf/1809.10270.pdf) -> No clear discussion on what is done regarding the congestion control (i.e. are the recovered pacekts ACKed or not ?). I am not really into this one as they basically state that using TCP for video streaming does not work well in general even with cases under 1% of losses and make claims such as this one: 
  > A recent study indicates that traffic policing is highly prevalent world-wide and induces, globally, an average loss rate of over 20% [10]: streaming video over TCP under such loss rates is infeasible.


Do not hesitate if you have other references. 

I think one good research "advice" we could point out is to include a discussion concerning the impact of the proposed FEC solution on the congestion control, especially loss-based congestion control such as cubic. There is often no discussion on that.

**Comment by NicoKos** [comment]
A new section on open research questions has been added

**Comment by mwelzl** [comment]
Some more, I think they're all "Inside transport":

- Flach, T., Dukkipati, N., Terzis, A., Raghavan, B., Cardwell, N., Cheng, Y., Jain, A., Hao, S., Katz-Bassett, E., and R. Govindan, "Reducing Web Latency: the Virtue of Gentle Aggression",
Proceedings of the 2013 ACM SIGCOMM , 2013.   (I think that's the same work as the now-expired draft-flach-tcpm-fec )
- Ferlin S, Kucera S, Claussen H, Alay Ö. MPTCP meets FEC: Supporting latency-sensitive applications over heterogeneous networks. IEEE/ACM Transactions on Networking. 2018 Aug 29;26(5):2005-18.  (this extends the Flach et al idea of "instant recovery" to MPTCP)
-  Baldantoni L, Lundqvist H, Karlsson G. Adaptive end-to-end FEC for improving TCP performance over wireless links. In2004 IEEE International Conference on Communications (IEEE Cat. No. 04CH37577) 2004 Jun 20 (Vol. 7, pp. 4023-4027). IEEE.
- Sato Y, Koga H, Ikenaga T. TCP using adaptive FEC to improve throughput performance in high-latency environments. IEICE Transactions on Communications. 2018.

**Comment by mwelzl** [comment]
For a high-level overview of this research, see: https://www.uio.no/studier/emner/matnat/ifi/IN5150/h20/lecture-slides/in5150-nc.pdf
