### ISSUE TITLE
Sentence unclear

### ISSUE THREAD

**Issue by elochin** [irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport#38]
In "The inputs to FEC (packets to work upon, and signaling from the receiver about losses and/or repaired symbols)"

"packets to work upon" ?? -> currently encoded packets ?

**Comment by NicoKos** [comment]
I commit an updated text for that :
"The inputs to FEC (incoming data packets (without repair symbols), and signaling
        from the receiver about losses and/or repaired symbols)
"

**Comment by elochin** [comment]
May be suppress internal parenthesis ? Otherwise OK

**Comment by NicoKos** [comment]
done directly on master branch
