### ISSUE TITLE
Missing ref to TENTET

### ISSUE THREAD

**Issue by NicoKos** [irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport#43]

**Comment by elochin** [comment]
There are two possibilities either:
- "Point-to-point transmetting method based on the use of an erasure coding scheme and TCP/IP protocol", ISAE-SUPAERO (2019) EP 3 432 500 A1, WO 2019015931 (A1). https://bit.ly/31RdXXX
- "On the joint use of TCP and Network Coding", Emmanuel Lochin, IETF'100 NWCRG session, November 2017. https://bit.ly/3jBAkGS

**Comment by patibulon** [comment]
Since this is IPR protected content I gather the IPR declaration is up to date?

**Comment by elochin** [comment]
Yes

**Comment by NicoKos** [comment]
done in PR #44
