### ISSUE TITLE
[nitpicking] TCP does not obtain the avaibale capacity from the network

### ISSUE THREAD

**Issue by francoismichel** [irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport#45]
Section 2, this part of text :

> but all the information a congestion control obtains from a network (e.g., TCP can estimate latency and the available capacity at the bottleneck).

Should we really say that TCP obtains the available capacity from the network ? In my view, TCP tries to estimate it by looking at several other metrics. The "receive-rate computed from acknowledgements" seems to me a better fit than "the available capacity". For me, estimating the available capacity is explicitely the goal of the CC. But maybe am I wrong on this one. Nitpicking, anyway :-)

**Comment by mwelzl** [comment]
I don't see the problem: the text that you quote says that it estimates it. Either way, I have no strong opinion, and this seems like nitpicking indeed  :)

**Comment by francoismichel** [comment]
For me, there was some mixing between the input and the output of the congestion control as we considered the available capacity at the bottleneck as closing part of the input. But re-reading this, I don't think saying this is wrong. Closing the issue, thank you and sorry !
