### ISSUE TITLE
We should not mention UDP for FEC-above-transport

### ISSUE THREAD

**Issue by francoismichel** [irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport#46]
In section 3.2, the following paragraph : 

> This approach requires that the transport protocol does not implement a fully reliable data transfer service (e.g., based on lost packet retransmission).  UDP is an example of a protocol for which this approach is relevant.  

I think we should not mention UDP as it does not integrate a congestion control, so I don't think we could consider it in our FEC-above-transport category (maybe should we rename those categories by FEC above congestion control instead, but later). maybe should we mention FEC over QUIC datagrams instead: QUIC datagrams are congestion-controlled but unreliable :-)

**Comment by NicoKos** [comment]
I think the discussion on FEC over unreliable QUIC datagrams is very interesting to have in the document - but maybe later

**Comment by NicoKos** [comment]
I think the FEC above transport is more general and covers multiple aspects that could be included in the transport layer

**Comment by mwelzl** [comment]
I agree with Francois' argument of not mentioning UDP - indeed it doesn't fit, and QUIC with datagrams fits better. But I also agree with doing this later - so my suggestion is to leave it with UDP for now, until we introduce QuIC: it's easier to understand with UDP being mentioned, I think.

**Comment by patibulon** [comment]
Knowing there are drafts on FEC and QUIC it could be wise to leave the related discussion there.

Marie-José Montpetit
marie@mjmontpetit.com

**Comment by NicoKos** [comment]
Done in PR #54
