### ISSUE TITLE
Point to draft-amend-iccrg-multipath-reordering-00

### ISSUE THREAD

**Issue by NicoKos** [irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport#62]
Should we point to https://tools.ietf.org/html/draft-amend-iccrg-multipath-reordering-00 ?

**Comment by mwelzl** [comment]
Counter-arguments: it's a new draft, and it's not a WG or RG item.
If this never gets published, one day we have an RFC pointing at an expired I-D. Is that valuable?  To some degree, perhaps... but - I wouldn't create that dependency unless we really have to.

**Comment by NicoKos** [comment]
I agree - it is just to have a discussion since this was discussed in ICCRG
