### ISSUE TITLE
The FEC channel carries source symbols

### ISSUE THREAD

**Issue by francoismichel** [irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport#65]
In section `2.1.  Separate channels, separate entities`

This is an echo from a previous issue  that was not really addressed or "resolved". I will rephrase the problem from scratch and let me know if you agree with me or not. :-)

We describe the FEC channel (maybe should we call it the Coding channel as repair symbols could also be sent a-posteriori) and say that it carries repair symbols while the CC channel carries source packets.

What do you think of rephrasing it like the following: "The CC channel carries network packets and the coding channel carries source symbols and repair symbols" ?

source symbols are an abstract view on the application (and sometimes control) data that we want to protect. For example, several source symbols could be present in a single network packet, or several network packets could form one single source symbol. This is why network packets can be very different than source symbols. This also goes in our vision that CC and NC are separated channels and separated entities: they do not even share the concept of packets. 

What do you think ?

**Comment by NicoKos** [comment]
I agree there was some confusion here. 
I tried to solve this in commit https://github.com/irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport/pull/72/commits/736076111e3e78a83a61909dd93d49188015eaeb of PR #72
