### ISSUE TITLE
Section 2.3 and Figure 4 not totally clear

### ISSUE THREAD

**Issue by francoismichel** [irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport#66]
I am not totally sure of the meaning of section 2.3 and Figure 4. More specifically: are we saying that multiple data streams transiting through one single protocol instance are out of the scope of the document ? Do we consider only one single stream on one single protocol instance ? If this is the case, does that mean that we do not consider QUIC's use-case ?  What makes me think all of this is the following sentence:

> The document considers one application layer stream as input packets above a combination of FEC and transport layers.

**Comment by NicoKos** [comment]
I hope PR #72 and in particular commit https://github.com/irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport/pull/72/commits/18a362d0d436fb995f9d99e7baf47a80ee16beb5 clarifies everything
