### ISSUE TITLE
avoid talking about linear systems

### ISSUE THREAD

**Issue by francoismichel** [irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport#67]
In section 2.4 :

>  In particular, if the codec does
>  not enable a subset of the linear system to be inverted, the
>  receiver would have to wait for a certain minimum amount of repair
>  packets before it can recover all the source packets.

Why are we talking about a linear system here ? To be more general on the recovery algorithms that are used, maybe should we use the term "block or window" instead of "linear system"

What do you think ?

**Comment by NicoKos** [comment]
The commit https://github.com/irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport/pull/72/commits/a18f1b9a5311bf17f87786d570a797575f695e11 of PR #72 makes it more general.
