### ISSUE TITLE
If the size of the window/block increase, the chances of recovering decrease

### ISSUE THREAD

**Issue by francoismichel** [irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport#68]
In section 2.4, we say the following:

> If the size
> of the encoding window (for Sliding Window Coding) and the size of
> the blocks (for Block Coding) are large, the chances of recovering
> the erased symbols would increase.  

Either I misunderstood the statement or the sentence is not true. In my opinion, with an equal number of sent repair symbols, if the window/block size is larger, the recovery probability is lower as they are likely more lost source symbols in the window/blocks (with a fixed number of repair symbols).

**Comment by NicoKos** [comment]
Could be clarified by commit https://github.com/irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport/pull/72/commits/0fa3b9d11fee996ec8f8372ad74288016d6208c7 of PR #72
