### ISSUE TITLE
Section 3, description of "fully reliable"

### ISSUE THREAD

**Issue by francoismichel** [irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport#69]
In section 3, we can read the following:

> This approach requires that the transport protocol does not implement
>  a fully reliable data transfer service (e.g., based on lost packet
>  retransmission).

I would emphasize on en in-order delivery which is the real problem for FEC here, as a reliable messaging system without in-order delivery would work.

I would thus replace the parenthesis by the following:

> (i.e. delivering the data in-order to the upper layer)

**Comment by mwelzl** [comment]
I agree but I'd use a different replacement: I think it's good to point out that this is about reliability from something different than coding, and the in-order issue is more than just a refinement in the bracket. So, I would suggest the following:

> This approach requires that the transport protocol does not implement
a fully reliable in-order data transfer service (e.g., like TCP).

**Comment by NicoKos** [comment]
Dealt with in commit https://github.com/irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport/pull/72/commits/f07be3918d43b48e4114a640e79072de358c735b of PR #72
