### ISSUE TITLE
"transport and FEC mechanism could be conjointly designed" for partial reliability

### ISSUE THREAD

**Issue by francoismichel** [irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport#71]
In section 4.6: 

> The application may require partial reliability.  In this case, the
> transport and FEC mechanisms could be conjointly designed.  As one
> example, the reliability offered by FEC may be sufficient, with no
>  retransmission required.  This depends on application needs and the
>  trade-off between latency and loss.  Partial reliability impacts the
>  type of FEC and type of codec that can be used, such as discussed in
>  Section 2.4.

With coding, you can recover packets a-priori and a-posteriori, so I do not see any conjoint design between coding and the transport layer: if you replace the retransission mechanism by coding, you are more general as you can also recover packets a-priori and coding can offer full reliability if needed or partial reliability if the full reliability is not necessary. So I do not see any need of a conjoint design here: simply replace the retransmission-based reliability mechanism by the coding-based one. I do not really understand what we are trying to say here talking about a conjoint design.

What do you think ?

**Comment by mwelzl** [comment]
I don't get it either... could we just remove this?

**Comment by NicoKos** [comment]
Commit https://github.com/irtf-nwcrg/draft-irtf-nwcrg-coding-and-congestion-in-transport/pull/72/commits/2c8913302b4fe99f26006c7c15066b4caa30c282 in PR #72 could solve it all.
